### ISSUE TITLE
Set up Kanban board

### ISSUE THREAD

**Issue by Juanse7793** [Juanse7793/Capstone-2#21]
https://github.com/Juanse7793/Capstone-2/projects/1

We are two people in this team @Juanse7793 and @isaacpitwa

**Comment by Amrhub** [comment]
# Approved ✔️ 

Your submission is approved there is nothing to add, I wish you, good luck guys, 🤩 
<img src="https://media0.giphy.com/media/YWLFeeS3uG39Jh9FRv/giphy.gif"/>
